### ISSUE TITLE
access kibana Dashboard

### ISSUE THREAD

**Issue by shadihh9** [Koodous/Koodous-issues#27]
summery
i access kibana Dashboard
step to create
1- gohttp://xxx.xxx.xxx.xxx:5601/app/kibana#/dashboards?_g=()&filter=
2- and see access done
imapct
can attacker access kibana  exposed
poc in attahemnt 

![133889292-96263f66-b039-409b-a3be-90dd95cd7803](https://user-images.githubusercontent.com/740106/133889944-a6c84ae2-24f6-4bf5-a48f-f903c32575cc.png)

**Comment by Nekmo** [comment]
Thanks for your report. We have disabled access to the affected machine until we check its status.

This is an old unused monitoring machine. Due to a change in the firewall it was exposed on the Internet. It has probably affected a short time, but we are going to check the machine for security reasons.
